/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgGridButton: typeof import('./components/AgGridButton.vue')['default']
    AgGridCellButton: typeof import('./components/AgGridCellButton.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ButtonGroup: typeof import('./components/ButtonGroup.vue')['default']
    Buttons: typeof import('./components/Buttons.vue')['default']
    CommonApiSelect_NEW: typeof import('./components/CommonApiSelect_NEW.vue')['default']
    CommonDatePicker: typeof import('./components/CommonDatePicker.vue')['default']
    CommonInput: typeof import('./components/CommonInput.vue')['default']
    CommonSelect: typeof import('./components/CommonSelect.vue')['default']
    CommonStaticSelect: typeof import('./components/CommonStaticSelect.vue')['default']
    copy: typeof import('./components/SelectApi copy.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElContaioner: typeof import('element-plus/es')['ElContaioner']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Input: typeof import('./components/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    SelectApi: typeof import('./components/SelectApi.vue')['default']
    SelectPassvie: typeof import('./components/SelectPassvie.vue')['default']
    SelectQuery: typeof import('./components/SelectQuery.vue')['default']
    SelectSearch: typeof import('./components/SelectSearch.vue')['default']
    SelectStatic: typeof import('./components/SelectStatic.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
