/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgGridCellButton: typeof import('./components/AgGridCellButton.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ButtonGroup: typeof import('./components/ButtonGroup.vue')['default']
    Buttons: typeof import('./components/Buttons.vue')['default']
    CommonApiSelect_NEW: typeof import('./components/CommonApiSelect_NEW.vue')['default']
    CommonDatePicker: typeof import('./components/CommonDatePicker.vue')['default']
    CommonInput: typeof import('./components/CommonInput.vue')['default']
    CommonSelect: typeof import('./components/CommonSelect.vue')['default']
    CommonStaticSelect: typeof import('./components/CommonStaticSelect.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    Input: typeof import('./components/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    SelectApi: typeof import('./components/SelectApi.vue')['default']
    SelectPassvie: typeof import('./components/SelectPassvie.vue')['default']
    SelectStatic: typeof import('./components/SelectStatic.vue')['default']
  }
}
